<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.1.0</version>
		<relativePath />
		<!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>25</java.version>
		<native-build-tools.version>1.1.8</native-build-tools.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webflux</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.graalvm.buildtools</groupId>
				<artifactId>native-maven-plugin</artifactId>
				<version>${native-build-tools.version}</version>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<image>
						<builder>paketobuildpacks/builder-jammy-buildpackless-tiny</builder>
						<buildpacks>
							<buildpack>paketobuildpacks/oracle</buildpack>
							<buildpack>paketobuildpacks/java-native-image</buildpack>
						</buildpacks>
					</image>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<id>instrumented</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<configuration>
							<imageName>${project.artifactId}-instrumented</imageName>
							<buildArgs>
								<buildArg>--pgo-instrument</buildArg>
							</buildArgs>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>optimized</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<configuration>
							<imageName>${project.artifactId}-optimized</imageName>
							<buildArgs>
								<buildArg>--gc=G1</buildArg>
								<buildArg>--pgo=${project.basedir}/default.iprof</buildArg>
								<buildArg>-march=native</buildArg>
							</buildArgs>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>monitored</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<configuration>
							<imageName>${project.artifactId}-monitored</imageName>
							<buildArgs>
								<buildArg>--pgo=${project.basedir}/default.iprof</buildArg>
								<buildArg>-march=native</buildArg>
								<buildArg>--enable-monitoring=heapdump,jfr,jvmstat</buildArg>
							</buildArgs>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>report</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<configuration>
							<imageName>${project.artifactId}-report</imageName>
							<buildArgs>
								<buildArg>--pgo</buildArg>
								<buildArg>--emit=build-report</buildArg>
								<buildArg>-H:+ReportDynamicAccess</buildArg>
								<buildArg>--enable-sbom=classpath,embed</buildArg>
							</buildArgs>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>sbom</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<configuration>
							<imageName>${project.artifactId}-sbom</imageName>
							<buildArgs>
								<buildArg>--enable-sbom=classpath,embed</buildArg>
							</buildArgs>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>size</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<configuration>
							<imageName>${project.artifactId}-size</imageName>
							<buildArgs>
								<buildArg>-Os</buildArg>
								<buildArg>-H:+MLCallCountProfileInference</buildArg>
							</buildArgs>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>static</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<configuration>
							<imageName>${project.artifactId}-static</imageName>
							<buildArgs>
								<buildArg>--static</buildArg>
								<buildArg>--libc=musl</buildArg>
							</buildArgs>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>static-size</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<configuration>
							<imageName>${project.artifactId}-static-size</imageName>
							<buildArgs>
								<buildArg>--static</buildArg>
								<buildArg>--libc=musl</buildArg>
								<buildArg>-Os</buildArg>
								<buildArg>-H:+MLCallCountProfileInference</buildArg>
							</buildArgs>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>preserve</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<configuration>
							<imageName>${project.artifactId}-preserve</imageName>
							<buildArgs>
								<buildArg>-H:+UnlockExperimentalVMOptions</buildArg>
								<buildArg>-H:Preserve=all</buildArg>
								<buildArg>-H:IgnorePreserveForClasses=org.springframework.web.servlet.mvc.ServletWrappingController
								</buildArg>
								<buildArg>-H:-UnlockExperimentalVMOptions</buildArg>
							</buildArgs>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>obfuscated</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<configuration>
							<imageName>${project.artifactId}-obfuscated</imageName>
							<buildArgs>
								<buildArg>-H:+UnlockExperimentalVMOptions</buildArg>
								<buildArg>-H:AdvancedObfuscation=export-mapping</buildArg>
								<buildArg>-H:-UnlockExperimentalVMOptions</buildArg>
							</buildArgs>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>pie</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<configuration>
							<imageName>${project.artifactId}-pie</imageName>
							<buildArgs>
								<buildArg>-H:NativeLinkerOption=-pie</buildArg>
							</buildArgs>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>pie-rcp</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<configuration>
							<imageName>${project.artifactId}-pie-rcp</imageName>
							<buildArgs>
								<buildArg>-H:NativeLinkerOption=-pie</buildArg>
								<buildArg>-H:+UnlockExperimentalVMOptions</buildArg>
								<buildArg>-H:+RelativeCodePointers</buildArg>
								<buildArg>-H:-UnlockExperimentalVMOptions</buildArg>
							</buildArgs>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>future-defaults</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<configuration>
							<imageName>${project.artifactId}-future-defaults</imageName>
							<buildArgs>
								<buildArg>--future-defaults=all</buildArg>
							</buildArgs>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>crema</id>
			<dependencies>
				<dependency>
					<groupId>net.bytebuddy</groupId>
					<artifactId>byte-buddy</artifactId>
				</dependency>
			</dependencies>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>build-helper-maven-plugin</artifactId>
						<version>3.6.1</version>
						<executions>
							<execution>
								<id>add-crema-source</id>
								<phase>generate-sources</phase>
								<goals>
									<goal>add-source</goal>
								</goals>
								<configuration>
									<sources>
										<source>src/crema/java</source>
									</sources>
								</configuration>
							</execution>
							<execution>
								<id>add-crema-test-source</id>
								<phase>generate-test-sources</phase>
								<goals>
									<goal>add-test-source</goal>
								</goals>
								<configuration>
									<sources>
										<source>src/crema-test/java</source>
									</sources>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.graalvm.buildtools</groupId>
						<artifactId>native-maven-plugin</artifactId>
						<configuration>
							<imageName>${project.artifactId}-crema</imageName>
							<buildArgs>
								<buildArg>-Ob</buildArg>
								<buildArg>--initialize-at-build-time=net.bytebuddy</buildArg>
								<buildArg>-H:+RuntimeClassLoading</buildArg>
							</buildArgs>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>

	</profiles>

</project>
