# docker build -f Dockerfiles/Dockerfile.native -t native-spring-boot-native:latest .
# docker run -p 8080:8080 native-spring-boot-native:latest .

# Using Oracle GraalVM 25.2
FROM container-registry.oracle.com/graalvm/native-image:25i2 AS builder

# Set the working directory to /home/app
WORKDIR /build

# Copy the source code into the image for building
COPY . /build

# Build
RUN ./mvnw --no-transfer-progress native:compile -Pnative

# The native executable needs a libc base, not a JVM runtime
FROM gcr.io/distroless/base-debian12:nonroot

EXPOSE 8080

# Copy the native executable into the containers
COPY --from=builder --chown=nonroot:nonroot /build/target/demo app
ENTRYPOINT ["/app"]
