# docker build -f Dockerfiles/Dockerfile.native.static.size -t native-spring-boot-static-size:latest .
# docker run -p 8080:8080 native-spring-boot-static-size:latest 

# Using Oracle GraalVM 25.2 with musl
FROM container-registry.oracle.com/graalvm/native-image:25i2-muslib AS builder

# Set the working directory to /home/app
WORKDIR /build

# Copy the source code into the image for building
COPY . /build

# Build
RUN ./mvnw --no-transfer-progress native:compile -Pnative,static-size

# A fully static executable can run in an empty image
FROM scratch

EXPOSE 8080

# Copy the native executable into the containers
COPY --from=builder /build/target/demo-static-size app
ENTRYPOINT ["/app"]
