# mvn static
# docker build -f Dockerfiles/Dockerfile.native.static --build-arg APP_FILE=demo-static -t native-spring-boot-static-scratch:latest .
# docker run -p 8080:8080 native-spring-boot-static-scratch:latest

FROM scratch

VOLUME /tmp

ARG APP_FILE
EXPOSE 8080

COPY target/${APP_FILE} app
ENTRYPOINT ["/app"]