# docker build -f Dockerfiles/Dockerfile.jdk.distroless -t native-spring-boot-jdk-distroless:latest .
# docker run -p 8080:8080 localhost/native-spring-boot-jdk-distroless:latest

# Using GraalVM 25.2
FROM container-registry.oracle.com/graalvm/jdk:25i2 AS build

# Set the working directory for build operations
WORKDIR /build

# Copy the project into the container
COPY . .

# Build
RUN ./mvnw package -DskipTests

# Run the JDK 25 application on a matching distroless runtime
FROM gcr.io/distroless/java25-debian12:nonroot

# Set the working dir
WORKDIR /app

# Copy the jar
COPY --from=build /build/target/demo-0.0.1-SNAPSHOT.jar /app/app.jar

# Expose the port
EXPOSE 8080

# Run
ENTRYPOINT ["java", "-jar", "app.jar"]
