name: GraalVM Native Image builds
on: push
#  schedule:
#    - cron: '00 10 * * MON'  # At 10:00 Monday
permissions:
  contents: write
jobs:
  build:
    name: Spring Boot Native Image on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          version: "25.2"
          java-version: "25"
          distribution: "graalvm"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: "maven"
          check-for-updates: "true"
          native-image-job-reports: "true"
          native-image-enable-sbom: "true"

      - name: Test on the JVM
        run: mvn --no-transfer-progress test

      - name: Build a native executable
        run: mvn --no-transfer-progress -Pnative native:compile

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: demo-${{ matrix.os }}
          path: |
            target/demo
